{
    "source": "BDSA",
    "name": "BDSA-2019-0819",
    "title": "Python Vulnerable to Arbitrary File Reads via 'local_file:' Scheme in 'urllib' Library",
    "description": "Python is vulnerable to arbitrary file reads due to improper support of the two schemes in the `urllib` library. An attacker could leverage this vulnerability to bypass blacklisted `file:` URI protections and read arbitrary files on a victim's system within the privileges of the targeted application.",
    "technicalDescription": "The `urllib` library in Python exposes the  `local_file:` and `local-file:` URI schemes with the function `open_local_file()` in the file `Lib/urllib.py`. If a vulnerable application only blacklists the `file:` scheme, this could allow an attacker to supply malicious `local_file:` URIs in order to read local files on a targeted system.",
    "publishedDate": "2019-04-01T14:35:28.313Z",
    "updatedDate": "2019-07-05T08:47:00.550Z",
    "disclosureDate": "2019-02-06T00:00:00.000Z",
    "exploitPublishDate": "2019-02-06T00:00:00.000Z",
    "solution": "* Fixed in **2.7** branch by [this](https://github.com/python/cpython/commit/b15bde8058e821b383d81fcae68b335a752083ca) commit.\n* Fixed in **3.6.9-rc1** by [this](https://github.com/python/cpython/commit/4f06dae5d8d4400ba38d8502da620f07d4a5696e) commit.\n* Fixed in **3.7.4-rc1** by [this](https://github.com/python/cpython/commit/34bab215596671d0dec2066ae7d7450cd73f638b) commit.\n* Fixed in **3.8.0-b1** by [this](https://github.com/python/cpython/commit/0c2b6a3943aa7b022e8eb4bfd9bffcddebf9a587) commit.\n\nThe latest stable releases are available [here](https://www.python.org/downloads/).",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 5.0,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 10.0,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "availabilityImpact": "NONE",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.9
        },
        "vector": "(AV:N/AC:L/Au:N/C:P/I:N/A:N/E:POC/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 7.5,
        "impactSubscore": 3.6,
        "exploitabilitySubscore": 3.9,
        "severity": "MEDIUM",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "NONE",
        "availabilityImpact": "NONE",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 6.7
        },
        "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N/E:P/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "credit": "Sihoon Lee",
    "workaround": "A proposed patch, which has not yet been reviewed, is available in [this](https://github.com/python/cpython/pull/11842) pull request. Please be aware that this patch may not be fully tested.",
    "vendorFixDate": "2019-05-22T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 6.7,
    "_meta": {
        "allow": [],
        "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/BDSA-2019-0819",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro.app.blackduck.com/api/cwes/CWE-20"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/CVE-2019-9948",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/BDSA-2019-0819/ranges"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue35907",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue35907",
                "label": "POC"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/0c2b6a3943aa7b022e8eb4bfd9bffcddebf9a587",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/34bab215596671d0dec2066ae7d7450cd73f638b",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/4f06dae5d8d4400ba38d8502da620f07d4a5696e",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/b15bde8058e821b383d81fcae68b335a752083ca",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/pull/11842",
                "label": "WORKAROUND"
            },
            {
                "rel": "reference",
                "href": "https://www.python.org/downloads/",
                "label": "VENDOR_UPGRADE"
            }
        ]
    }
}